### ISSUE TITLE
Todo : Doesn't work on other python terminals. Should make it do.

### ISSUE THREAD

**Issue by rohithasrk** [vinamarora8/PyTerm-Colors#2]
The program doesn't work on other python shells like ipython and etc., which makes it's utility a little lesser.

**Comment by vinamarora8** [comment]
This is not supposed to be used with shells anyway. It is meant to make colored terminal programs, not colored shells.
Plus, ipython does its own color thingy when writing a new line, for which I think the method used in this program is not going to do the trick.

**Comment by rohithasrk** [comment]
I'm afraid I don't understand whats happening in the below terminal.

![whatsthis](https://cloud.githubusercontent.com/assets/13820931/21010690/85a3f64e-bd73-11e6-96c3-b6a4df14fa41.png)

**Comment by rohithasrk** [comment]
Is this the way it is supposed to be used?

**Comment by vinamarora8** [comment]
This is how it is supposed to be used. Not meant to be used in the python shell, but in the end user application.

![screenshot from 2016-12-09 06-55-16](https://cloud.githubusercontent.com/assets/15000028/21034288/b85a656e-bddc-11e6-9212-8f442eead281.png)
![screenshot from 2016-12-09 06-56-06](https://cloud.githubusercontent.com/assets/15000028/21034289/b8c7b542-bddc-11e6-9e49-284090b58894.png)

**Comment by vinamarora8** [comment]
I understand the instructions in README.md are insufficient.
So I have added instruction pictures to it as well now.

**Comment by rohithasrk** [comment]
Oh! I get it. Thanks. :+1:
